[package]
name = "nemesisx00-github-io"
version = "1.0.0"
authors = ["Peter Lunneberg"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "~0.4"
dioxus-web = "~0.4"
log = "~0"
# WebAssembly Debug
wasm-logger = "~0"
console_error_panic_hook = "~0"
