name: Deploy Page

on:
  #push:
  #  branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt-get update
          curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - && sudo apt-get install -y nodejs
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          rustup target add wasm32-unknown-unknown
          cargo install dioxus-cli
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Subprojects
        run: |
          npm install --prefix ./subprojects/novas-run
      
      - name: Build
        run: |
          npm install
          dx build --release
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{github.workspace}}/web'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
