name: Deploy Page

on:
  #push:
  #  branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Setup Rust & Dioxus CLI
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          rustup target add wasm32-unknown-unknown
          cargo install dioxus-cli
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Subprojects
        run: |
          npm install --prefix ./subprojects/novas-run
      
      - name: Build
        run: |
          npm install
          dx build --release
      
      - name: Add fallback file
        run: |
          cp '${{github.workspace}}/web/index.html' '${{github.workspace}}/web/404.html'
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{github.workspace}}/web'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
